name: untitled1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_sizer: ^1.0.5
  sizer: ^2.0.15
  iconly: ^1.0.1
  animate_do: ^3.3.4
  image_picker: ^1.1.1 
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  community_material_icon: ^5.9.55
  open_file: ^3.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_credit_card: ^4.0.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  flutter_hooks: any
  hooks_riverpod: any
  day_night_switch: ^1.0.4
  provider: ^6.0.0
  flutter_riverpod: ^2.5.1
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.0.1
  local_auth: ^2.2.0
  flutter_paypal_payment: ^1.0.6
  firebase_auth: 4.20.0
  firebase_core: ^2.5.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  flutter_stripe: ^10.2.0
  
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Images/1024.png"
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    -  assets/Images/
    -  assets/icons/
    -  assets/text/ 

  fonts:
    - family: Arimo
      fonts:
        - asset: fonts/Arimo-VariableFont_wght.ttf
        
    - family: Voltaire
      fonts:
        - asset: fonts/Voltaire-Regular.ttf

    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Light.ttf
          weight: 200
        - asset: fonts/Satoshi-Regular.ttf
          weight: 300
        - asset: fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: fonts/Satoshi-Bold.ttf
          weight: 500



